name: MoreGear
version: '${project.version}'
main: de.tomino.moregear.MoreGear
api-version: 1.19
authors: [ Tomino_LP ]
description: A Plugin that adds more gear to th game
website: github.com/TominoLP/MoreGear
commands:
  test:

